services:
  minvault:
    image: minvault
    container_name: minvault
    hostname: minvault
    ports:
      - 8200:8200
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - /opt/vault/data:/vault/file/
      - ./vault-root-token:/vault/file/vault-root-token
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

volumes:
  data:
